In [1]:
from sqlalchemy import create_engine
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv(r'C:\Users\VANT\ironhack\ejercicios\w3-project_SQL\data\film.csv')

data

,film_id,title,description,release_year,language_id,original_language_id,rental_duration,rental_rate,length,replacement_cost,rating,special_features,last_update
0,1,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,2006,1,NaN,6,0.99,86,20.99,PG,"Deleted Scenes,Behind the Scenes",2006-02-15 05:03:42
1,2,ACE GOLDFINGER,A Astounding Epistle of a Database Administrat...,2006,1,NaN,3,4.99,48,12.99,G,"Trailers,Deleted Scenes",2006-02-15 05:03:42
2,3,ADAPTATION HOLES,A Astounding Reflection of a Lumberjack And a ...,2006,1,NaN,7,2.99,50,18.99,NC-17,"Trailers,Deleted Scenes",2006-02-15 05:03:42
3,4,AFFAIR PREJUDICE,A Fanciful Documentary of a Frisbee And a Lumb...,2006,1,NaN,5,2.99,117,26.99,G,"Commentaries,Behind the Scenes",2006-02-15 05:03:42
4,5,AFRICAN EGG,A Fast-Paced Documentary of a Pastry Chef And ...,2006,1,NaN,6,2.99,130,22.99,G,Deleted Scenes,2006-02-15 05:03:42
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,YOUNG LANGUAGE,A Unbelieveable Yarn of a Boat And a Database ...,2006,1,NaN,6,0.99,183,9.99,G,"Trailers,Behind the Scenes",2006-02-15 05:03:42
996,997,YOUTH KICK,A Touching Drama of a Teacher And a Cat who mu...,2006,1,NaN,4,0.99,179,14.99,NC-17,"Trailers,Behind the Scenes",2006-02-15 05:03:42
997,998,ZHIVAGO CORE,A Fateful Yarn of a Composer And a Man who mus...,2006,1,NaN,6,0.99,105,10.99,NC-17,Deleted Scenes,2006-02-15 05:03:42
998,999,ZOOLANDER FICTION,A Fateful Reflection of a Waitress And a Boat ...,2006,1,NaN,5,2.99,101,28.99,R,"Trailers,Deleted Scenes",2006-02-15 05:03:42
999,1000,ZORRO ARK,A Intrepid Panorama of a Mad Scientist And a B...,2006,1,NaN,3,4.99,50,18.99,NC-17,"Trailers,Commentaries,Behind the Scenes",2006-02-15 05:03:42

In [3]:
nan_cols= data.isna().sum()

nan_cols

film_id                    0
title                      0
description                0
release_year               0
language_id                0
original_language_id    1000
rental_duration            0
rental_rate                0
length                     0
replacement_cost           0
rating                     0
special_features           0
last_update                0
dtype: int64

In [4]:
original_language_ids = []

for i in range(len(data)):
    original_language_ids.append(i+1)
    
data['original_language_id'] = original_language_ids

In [5]:
nan_cols

film_id                    0
title                      0
description                0
release_year               0
language_id                0
original_language_id    1000
rental_duration            0
rental_rate                0
length                     0
replacement_cost           0
rating                     0
special_features           0
last_update                0
dtype: int64

In [6]:
data

,film_id,title,description,release_year,language_id,original_language_id,rental_duration,rental_rate,length,replacement_cost,rating,special_features,last_update
0,1,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,2006,1,1,6,0.99,86,20.99,PG,"Deleted Scenes,Behind the Scenes",2006-02-15 05:03:42
1,2,ACE GOLDFINGER,A Astounding Epistle of a Database Administrat...,2006,1,2,3,4.99,48,12.99,G,"Trailers,Deleted Scenes",2006-02-15 05:03:42
2,3,ADAPTATION HOLES,A Astounding Reflection of a Lumberjack And a ...,2006,1,3,7,2.99,50,18.99,NC-17,"Trailers,Deleted Scenes",2006-02-15 05:03:42
3,4,AFFAIR PREJUDICE,A Fanciful Documentary of a Frisbee And a Lumb...,2006,1,4,5,2.99,117,26.99,G,"Commentaries,Behind the Scenes",2006-02-15 05:03:42
4,5,AFRICAN EGG,A Fast-Paced Documentary of a Pastry Chef And ...,2006,1,5,6,2.99,130,22.99,G,Deleted Scenes,2006-02-15 05:03:42
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,YOUNG LANGUAGE,A Unbelieveable Yarn of a Boat And a Database ...,2006,1,996,6,0.99,183,9.99,G,"Trailers,Behind the Scenes",2006-02-15 05:03:42
996,997,YOUTH KICK,A Touching Drama of a Teacher And a Cat who mu...,2006,1,997,4,0.99,179,14.99,NC-17,"Trailers,Behind the Scenes",2006-02-15 05:03:42
997,998,ZHIVAGO CORE,A Fateful Yarn of a Composer And a Man who mus...,2006,1,998,6,0.99,105,10.99,NC-17,Deleted Scenes,2006-02-15 05:03:42
998,999,ZOOLANDER FICTION,A Fateful Reflection of a Waitress And a Boat ...,2006,1,999,5,2.99,101,28.99,R,"Trailers,Deleted Scenes",2006-02-15 05:03:42
999,1000,ZORRO ARK,A Intrepid Panorama of a Mad Scientist And a B...,2006,1,1000,3,4.99,50,18.99,NC-17,"Trailers,Commentaries,Behind the Scenes",2006-02-15 05:03:42

In [7]:
nan_cols

film_id                    0
title                      0
description                0
release_year               0
language_id                0
original_language_id    1000
rental_duration            0
rental_rate                0
length                     0
replacement_cost           0
rating                     0
special_features           0
last_update                0
dtype: int64

In [8]:
data['last_update'] = pd.to_datetime(data['last_update'])
data['last_date'] = data['last_update'].dt.floor('D')
data['last_update'] = pd.to_datetime(data['last_update'])

data['last_hour'] = data['last_update'].dt.time
data.drop(columns=['last_update'], inplace=True)

In [9]:
data

,film_id,title,description,release_year,language_id,original_language_id,rental_duration,rental_rate,length,replacement_cost,rating,special_features,last_date,last_hour
0,1,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,2006,1,1,6,0.99,86,20.99,PG,"Deleted Scenes,Behind the Scenes",2006-02-15,05:03:42
1,2,ACE GOLDFINGER,A Astounding Epistle of a Database Administrat...,2006,1,2,3,4.99,48,12.99,G,"Trailers,Deleted Scenes",2006-02-15,05:03:42
2,3,ADAPTATION HOLES,A Astounding Reflection of a Lumberjack And a ...,2006,1,3,7,2.99,50,18.99,NC-17,"Trailers,Deleted Scenes",2006-02-15,05:03:42
3,4,AFFAIR PREJUDICE,A Fanciful Documentary of a Frisbee And a Lumb...,2006,1,4,5,2.99,117,26.99,G,"Commentaries,Behind the Scenes",2006-02-15,05:03:42
4,5,AFRICAN EGG,A Fast-Paced Documentary of a Pastry Chef And ...,2006,1,5,6,2.99,130,22.99,G,Deleted Scenes,2006-02-15,05:03:42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,YOUNG LANGUAGE,A Unbelieveable Yarn of a Boat And a Database ...,2006,1,996,6,0.99,183,9.99,G,"Trailers,Behind the Scenes",2006-02-15,05:03:42
996,997,YOUTH KICK,A Touching Drama of a Teacher And a Cat who mu...,2006,1,997,4,0.99,179,14.99,NC-17,"Trailers,Behind the Scenes",2006-02-15,05:03:42
997,998,ZHIVAGO CORE,A Fateful Yarn of a Composer And a Man who mus...,2006,1,998,6,0.99,105,10.99,NC-17,Deleted Scenes,2006-02-15,05:03:42
998,999,ZOOLANDER FICTION,A Fateful Reflection of a Waitress And a Boat ...,2006,1,999,5,2.99,101,28.99,R,"Trailers,Deleted Scenes",2006-02-15,05:03:42
999,1000,ZORRO ARK,A Intrepid Panorama of a Mad Scientist And a B...,2006,1,1000,3,4.99,50,18.99,NC-17,"Trailers,Commentaries,Behind the Scenes",2006-02-15,05:03:42

In [10]:
language_ids = []

for i in range(len(data)):
    language_ids.append(i+1)

data['language_id'] = language_ids

In [11]:
data

,film_id,title,description,release_year,language_id,original_language_id,rental_duration,rental_rate,length,replacement_cost,rating,special_features,last_date,last_hour
0,1,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,2006,1,1,6,0.99,86,20.99,PG,"Deleted Scenes,Behind the Scenes",2006-02-15,05:03:42
1,2,ACE GOLDFINGER,A Astounding Epistle of a Database Administrat...,2006,2,2,3,4.99,48,12.99,G,"Trailers,Deleted Scenes",2006-02-15,05:03:42
2,3,ADAPTATION HOLES,A Astounding Reflection of a Lumberjack And a ...,2006,3,3,7,2.99,50,18.99,NC-17,"Trailers,Deleted Scenes",2006-02-15,05:03:42
3,4,AFFAIR PREJUDICE,A Fanciful Documentary of a Frisbee And a Lumb...,2006,4,4,5,2.99,117,26.99,G,"Commentaries,Behind the Scenes",2006-02-15,05:03:42
4,5,AFRICAN EGG,A Fast-Paced Documentary of a Pastry Chef And ...,2006,5,5,6,2.99,130,22.99,G,Deleted Scenes,2006-02-15,05:03:42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,YOUNG LANGUAGE,A Unbelieveable Yarn of a Boat And a Database ...,2006,996,996,6,0.99,183,9.99,G,"Trailers,Behind the Scenes",2006-02-15,05:03:42
996,997,YOUTH KICK,A Touching Drama of a Teacher And a Cat who mu...,2006,997,997,4,0.99,179,14.99,NC-17,"Trailers,Behind the Scenes",2006-02-15,05:03:42
997,998,ZHIVAGO CORE,A Fateful Yarn of a Composer And a Man who mus...,2006,998,998,6,0.99,105,10.99,NC-17,Deleted Scenes,2006-02-15,05:03:42
998,999,ZOOLANDER FICTION,A Fateful Reflection of a Waitress And a Boat ...,2006,999,999,5,2.99,101,28.99,R,"Trailers,Deleted Scenes",2006-02-15,05:03:42
999,1000,ZORRO ARK,A Intrepid Panorama of a Mad Scientist And a B...,2006,1000,1000,3,4.99,50,18.99,NC-17,"Trailers,Commentaries,Behind the Scenes",2006-02-15,05:03:42

In [12]:
data.drop_duplicates()

,film_id,title,description,release_year,language_id,original_language_id,rental_duration,rental_rate,length,replacement_cost,rating,special_features,last_date,last_hour
0,1,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,2006,1,1,6,0.99,86,20.99,PG,"Deleted Scenes,Behind the Scenes",2006-02-15,05:03:42
1,2,ACE GOLDFINGER,A Astounding Epistle of a Database Administrat...,2006,2,2,3,4.99,48,12.99,G,"Trailers,Deleted Scenes",2006-02-15,05:03:42
2,3,ADAPTATION HOLES,A Astounding Reflection of a Lumberjack And a ...,2006,3,3,7,2.99,50,18.99,NC-17,"Trailers,Deleted Scenes",2006-02-15,05:03:42
3,4,AFFAIR PREJUDICE,A Fanciful Documentary of a Frisbee And a Lumb...,2006,4,4,5,2.99,117,26.99,G,"Commentaries,Behind the Scenes",2006-02-15,05:03:42
4,5,AFRICAN EGG,A Fast-Paced Documentary of a Pastry Chef And ...,2006,5,5,6,2.99,130,22.99,G,Deleted Scenes,2006-02-15,05:03:42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,YOUNG LANGUAGE,A Unbelieveable Yarn of a Boat And a Database ...,2006,996,996,6,0.99,183,9.99,G,"Trailers,Behind the Scenes",2006-02-15,05:03:42
996,997,YOUTH KICK,A Touching Drama of a Teacher And a Cat who mu...,2006,997,997,4,0.99,179,14.99,NC-17,"Trailers,Behind the Scenes",2006-02-15,05:03:42
997,998,ZHIVAGO CORE,A Fateful Yarn of a Composer And a Man who mus...,2006,998,998,6,0.99,105,10.99,NC-17,Deleted Scenes,2006-02-15,05:03:42
998,999,ZOOLANDER FICTION,A Fateful Reflection of a Waitress And a Boat ...,2006,999,999,5,2.99,101,28.99,R,"Trailers,Deleted Scenes",2006-02-15,05:03:42
999,1000,ZORRO ARK,A Intrepid Panorama of a Mad Scientist And a B...,2006,1000,1000,3,4.99,50,18.99,NC-17,"Trailers,Commentaries,Behind the Scenes",2006-02-15,05:03:42

In [13]:
data['trailers'] = [1 if 'trailers' in str(feature).lower() else 0 for feature in data['special_features']]
data['deleted_sences'] = [1 if 'deleted' in str(feature).lower() else 0 for feature in data['special_features']]
data['commentaries'] = [1 if 'commentaries' in str(feature).lower() else 0 for feature in data['special_features']]
data['behind_the_sences'] = [1 if 'behind' in str(feature).lower() else 0 for feature in data['special_features']]

In [17]:
data.drop(columns=['special_features'],inplace=True)

In [18]:
data

,film_id,title,description,release_year,language_id,original_language_id,rental_duration,rental_rate,length,replacement_cost,rating,last_date,last_hour,trailers,deleted_sences,commentaries,behind_the_sences
0,1,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,2006,1,1,6,0.99,86,20.99,PG,2006-02-15,05:03:42,0,1,0,1
1,2,ACE GOLDFINGER,A Astounding Epistle of a Database Administrat...,2006,2,2,3,4.99,48,12.99,G,2006-02-15,05:03:42,1,1,0,0
2,3,ADAPTATION HOLES,A Astounding Reflection of a Lumberjack And a ...,2006,3,3,7,2.99,50,18.99,NC-17,2006-02-15,05:03:42,1,1,0,0
3,4,AFFAIR PREJUDICE,A Fanciful Documentary of a Frisbee And a Lumb...,2006,4,4,5,2.99,117,26.99,G,2006-02-15,05:03:42,0,0,1,1
4,5,AFRICAN EGG,A Fast-Paced Documentary of a Pastry Chef And ...,2006,5,5,6,2.99,130,22.99,G,2006-02-15,05:03:42,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,YOUNG LANGUAGE,A Unbelieveable Yarn of a Boat And a Database ...,2006,996,996,6,0.99,183,9.99,G,2006-02-15,05:03:42,1,0,0,1
996,997,YOUTH KICK,A Touching Drama of a Teacher And a Cat who mu...,2006,997,997,4,0.99,179,14.99,NC-17,2006-02-15,05:03:42,1,0,0,1
997,998,ZHIVAGO CORE,A Fateful Yarn of a Composer And a Man who mus...,2006,998,998,6,0.99,105,10.99,NC-17,2006-02-15,05:03:42,0,1,0,0
998,999,ZOOLANDER FICTION,A Fateful Reflection of a Waitress And a Boat ...,2006,999,999,5,2.99,101,28.99,R,2006-02-15,05:03:42,1,1,0,0
999,1000,ZORRO ARK,A Intrepid Panorama of a Mad Scientist And a B...,2006,1000,1000,3,4.99,50,18.99,NC-17,2006-02-15,05:03:42,1,0,1,1

In [19]:
data.to_csv(r'C:\Users\VANT\ironhack\ejercicios\w3-project_SQL\film_actor.csv', index=False)